### PR TITLE
Fix build in VS2022

### PR DESCRIPTION
**Pull request by kant2002**
That's improve status after https://github.com/microsoft/TestWinRT/pull/53
and required to fully compliment https://github.com/microsoft/CsWinRT/pull/1217

### CODE REVIEW

**Comment by manodasanW** [comment]
@kant2002 thanks for updating these.  It looks like I am seeing some errors when building under VS 2022.

D:\src\CsWinRT\src\_build\x64\Release\TestComponent\obj\Generated Files\winrt\base.h(6890,20): error C2672: 'to_abi': no matching overloaded function found [D:\src\CsWinRT\src\TestWinRT\TestComponent\TestComponent.vcxproj]

I looked into it and if you were to update this [line ](https://github.com/microsoft/TestWinRT/blob/f6178d2ff40dcff5d0b3e382d25baea723d3567a/TestComponent/TestComponent.idl#L291)as below, it should resolve the C++ conformance error.

From

    unsealed runtimeclass Derived : Composable, IRequiredOne, IRequiredTwo, IRequiredThree, IRequiredFour

To

    unsealed runtimeclass Derived : Composable

as the interfaces are already declared on the base class and not reimplemented by the Derived class.

**Comment by sylveon** [comment]
As a sidenote, this should have never compiled to begin with. According to https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system:

> A class may not implement any interfaces defined on the class it composes, nor any class in the composition chain, unless the interface is marked as overridable in the composable class. Details on overridable interfaces to follow.

**Comment by manodasanW** [comment]
> As a sidenote, this should have never compiled to begin with. According to https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system:
> 
> > A class may not implement any interfaces defined on the class it composes, nor any class in the composition chain, unless the interface is marked as overridable in the composable class. Details on overridable interfaces to follow.

@sylveon Thanks for that pointer.  @DefaultRyan and I were talking about this earlier and it is strange that this wasn't a MIDL error, but just happened to work with VS 2019.

**Review by manodasanW — APPROVED** [review]

**Pull request merged**
